  version: "3"
  services:
    microService:
      image: staff:1.0.1
      container_name: staff
      ports:
        - "8082:8082"
      volumes:
        - /usr/lax/staff/:/data
      networks:
        - my_network
      depends_on:
         # - redis
          - mysql
  #
  #  redis:
  #    image: redis:7.0.5
  #    ports:
  #      -"6379:6379"
  #    volumes :
  #      - /app/redis/redis.conf:/etc/redis/redis.conf
  #      - /app/redis/data:/data
  #    networks:
  #     - my_network
  #    command: redis-server /etc/redis/redis.conf
    mysql:
       image: mysql:8.0.29
       environment:
          MYSQL_ROOT_PASSWORD: '123156'
          MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
          MYSOL DATABASE: 'db_user'
          MYSOL USER: 'root'
          MYSQL_PASSWORD: '123456'
       ports:
          - "3306:3306"
       volumes:
          - /usr/liuax/mysql/master/db:/var/lib/mysql
          - /usr/liuax/mysql/master/conf/my.cnf:/etc/my.cnf
          - /usr/liuax/mysql/master/init:/docker-entrypoint-initdb.d
       networks:
          - my_network
       command:
        --default-authentication-plugin=mysql_native_password #解决外部无法访问

  networks:
    my_network:
